### PR TITLE
Traction conditions

### PR DESCRIPTION
**Pull request by thoeschler**

### CODE REVIEW

**Comment by sebglane** [comment]
> The problem of a missing jacobi weight when using a nonstandard domain was apparently fixed in [this commit](https://github.com/spectralDNS/shenfun/commit/ae8fff349b6e55d0da080a5e28ece28c2d052852).

Does this fix the overall problem?

**Comment by thoeschler** [comment]
> > The problem of a missing jacobi weight when using a nonstandard domain was apparently fixed in [this commit](https://github.com/spectralDNS/shenfun/commit/ae8fff349b6e55d0da080a5e28ece28c2d052852).
> 
> Does this fix the overall problem?

Yes, I had fixed it manually in a previous commit by introducing a jacobi term. But since it is now implemented in shenfun I removed it again. All tests run with sufficient accuracy now.

**Comment by sebglane** [comment]
> Yes, I had fixed it manually in a previous commit by introducing a jacobi term. But since it is now implemented in shenfun I removed it again. All tests run with sufficient accuracy now.

Okay that's great! Are these tests already running in the test machine which I configured a while ago? If not, I can take care of this.

**Comment by thoeschler** [comment]
> Okay that's great! Are these tests already running in the test machine which I configured a while ago? If not, I can take care of this.

I think the test machine simply runs the test file but does not check for accuracy. I think this still needs to be implemented.

**Comment by sebglane** [comment]
In [d6aa43f](https://github.com/thoeschler/shenfun_elasticity/pull/10/commits/d6aa43fd925a657ede0c9523d1ad98ffe3d724cc), I added assertions which guarantee that the accuracies are achieved in the test.

This is ready to go on my end.

**Pull request merged**
